[main]
font=monospace:size=9
pad=15x15

[colors]
alpha=0.9
background=0b111a
foreground=e2f1f8

## Normal/regular colors
regular0=1e2d3b  # black (nieaktywny)
regular1=ff5e00  # red (plazmowy pomarańcz)
regular2=00f0d8  # green (neon teal)
regular3=ff5e00  # yellow 
regular4=00f0d8  # blue 
regular5=ff5e00  # magenta
regular6=00f0d8  # cyan
regular7=e2f1f8  # white (jasny tekst)

## Bright colors (żeby pogrubiony tekst w terminalu lśnił)
bright0=1e2d3b   
bright1=ff5e00   
bright2=00f0d8   
bright3=ff5e00   
bright4=00f0d8   
bright5=ff5e00   
bright6=00f0d8   
bright7=ffffff
