general {
    after_sleep_cmd = sleep 0.3 && hyprctl dispatch movecursor 1 1
    lock_cmd = pidof hyprlock || hyprlock
    inhibit_sleep = 0
    ignore_systemd_inhibit = true
}

listener {
    timeout = 300
    on-timeout = hyprlock
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1200
    on-timeout = doas pm-suspend
}
