preload = /home/mb/Obrazy/hyprland_Wallpapers/Gemini_Generated_Image_z5zmktz5zmktz5zm.png
wallpaper = eDP-1,/home/mb/Obrazy/hyprland_Wallpapers/Gemini_Generated_Image_z5zmktz5zmktz5zm.png
splash = false

