general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    brightness = 0.65
}

input-field {
    monitor =
    size = 320, 60
    outline_thickness = 2
    outer_color = rgba(00D8C3FF)
    inner_color = rgba(0B111ADD)
    font_color = rgba(E2F1F8FF)
    placeholder_text = Hasło...
    fail_color = rgba(D94A64FF)
    rounding = 12
    position = 0, -40
    halign = center
    valign = center
}
