---
icon: &icon Material Design Icons:style=Regular:pixelsize=18
tags: &tags Material Design Icons:style=Regular:pixelsize=22

bar:
  height: 27
  location: top
  layer: bottom
  spacing: 5
  font: Exo 2:size=20:weight=thin
  right-margin: 16
  left-margin: 16
  background: 11111155
  foreground: c5cdd4ff

  right:
    - clock:
        date-format: "%A, %d/%m/%Y"
        content:
          list:
            items:
              - string:
                  text: "{date}"
                  font: Exo 2:size=22:weight=light
                  foreground: 00FFFFff
              - string:
                  text: ""                  
#    - script:
#            path: /home/mb/.config/yambar/scripts/brightness_vu.fish
#            poll-interval: 1000
#            content:
#              list:
#                items:
#                  - string: {text: "", foreground: c5cdd4ff}
#                  - string: {text: "{brightness}", font: Exo 2:size=20:weight=light}
#                  - string: {text: "", foreground: 777777ff}                  
    - battery:
        name: BAT0
        poll-interval: 1000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                   tag: capacity
                   items:
                    - string: {text: "󰂃 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
                    - string: {text: "󰂃 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
                    - string: {text: "󰁼 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
                    - string: {text: "󰁽 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
                    - string: {text: "󰁾 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
                    - string: {text: "󰁿 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
                    - string: {text: "󰂀 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
                    - string: {text: "󰂁 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
                    - string: {text: "󰂂 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
                    - string: {text: "󰁹 {capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                list:
                  items:
                   - string: {text: "󰂄 "}
                   - string: {text: "{capacity}%", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}
              state == full:
                list:
                  items:
                   - string: {text: "󱟢 ", foreground: c5cdd4ff}
                   - string: {text: "FULL ", font: Exo 2:size=22:weight=light, foreground: c5cdd4ff}

  center:
    - clock:
        time-format: "%H:%M:%S"
        content:
          string:
            text: "{time}"
            font: Exo 2:size=22:weight=light
            foreground: 00FFFFff

  left:
    - network:
        poll-interval: 1000
        content:
          map:
            conditions:
              name == wlan0:
                map:
                  conditions:
                    state == up:
                      list:
                        items:
                          - string: {text: "NET: ", foreground: c5cdd4ff}
                          - string: {text: "({ipv4})", font: Exo 2:size=20:weight=light, foreground: c5cdd4ff}
                          - string: {text: " | ", foreground: 777777ff}
                    state == down:
                      list:
                        items:
                          - string: {text: "NET: ", foreground: c5cdd4ff}
                          - string: {text: "OFF", font: Exo 2:size=20:weight=light, foreground: c5cdd4ff}
                          - string: {text: " | ", foreground: 777777ff}

    - script:
        path: /home/mb/.config/yambar/scripts/cpu_info.fish
        poll-interval: 2000
        content:
          list:
            items:
              - string: {text: "CPU: ", foreground: c5cdd4ff}
              - string: {text: "{load}% {freq} MHz ({temp}°C)", font: Exo 2:size=20:weight=light, foreground: c5cdd4ff}
              - string: {text: " | ", foreground: 777777ff}

    - script:
        path: /home/mb/.config/yambar/scripts/vol_db.fish
        poll-interval: 1000
        content:
          list:
            items:
              - string: {text: "SND: ", foreground: c5cdd4ff}
              - string: {text: "{vol_state}", font: Exo 2:size=20:weight=light, foreground: c5cdd4ff}
              - string: {text: " | ", foreground: 777777ff}

    - disk-io:
        poll-interval: 1000
        content:
          map:
            conditions:
              device == nvme0n1:
                list:
                  items:
                    - string: {text: "DSK: ", foreground: c5cdd4ff}
                    - string: {text: "R:{read_speed:mib}MB/s W:{write_speed:mib}MB/s", font: Exo 2:size=20:weight=light, foreground: c5cdd4ff}
                    - string: {text: " | ", foreground: 777777ff}
